### ISSUE TITLE
Spread not working

### ISSUE THREAD

**Issue by skyrpex** [luwanquan/babel-preset-vca-jsx#2]
Hi there! I'm not sure if this belongs here, so sorry if it doesn't.

The first version correctly recognizes the types of the props, but won't work for Vue. Maybe this plugin could act differently when spreading? 

![image](https://user-images.githubusercontent.com/1077520/67495125-b551f100-f67a-11e9-970d-a6116ac97f73.png)

**Comment by luwanquan** [comment]
I am sorry that my reply is late.
I am not sure if I fully understand your question.

Under `.js`, both versions can be executed normally and correctly spread.

If you mean that the type is not recognized correctly under `.tsx`, can you provide a specific example?

But I believe this has nothing to do with this plugin.

**Comment by skyrpex** [comment]
That's not late, don't worry! :)

Sorry, the issue description was vague. You're right, it doesn't really belong here. I created an extended issue here: https://github.com/vuejs/babel-plugin-transform-vue-jsx/issues/182.
