### ISSUE TITLE
VCA-JSX not co-op with Babel @vue/app anymore

### ISSUE THREAD

**Issue by TrungRueta** [luwanquan/babel-preset-vca-jsx#3]
Hi, i hope you guy good health!

I want report 2 problem:

1. In our document explain how to add vca-jsx into babel config with vue cli = `@vue/app` but in vue cli nowadays they use `@vue/cli-plugin-babel/preset`. Can we update document ?

2. ~~document explains that with functional component we have format function with first argument is props. but actually when render i see first argument is CTX (`FunctionalRenderContext`). After a hour debug source code i found that because @vue present take care convert jsx into a vue object with first argument of render = ctx, and vca skipped transpile later. I'm not good enough to modify babel plugin code, can you guy take a look.~~
I found that functional component should return function, while i return direct JSX.Element and it only take care from vue cli present. This is not bug, it my fault but i think we should leave notice in document.

Thank you!

**Comment by mesqueeb** [comment]
+1

**Comment by luwanquan** [comment]
Thanks for the suggestion

I have updated to v0.3.3，Fixed [@vue/babel-sugar-v-model@1.1.2](https://github.com/vuejs/jsx/tree/dev/packages/babel-sugar-v-model) calling `this` in `setup()`

All your suggestions have been accepted and updated
